'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class SiteResources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SCrawler.SiteResources", GetType(SiteResources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property InstagramIcon_32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("InstagramIcon_32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property InstagramPic_76() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InstagramPic_76", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property JFFIcon_64() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("JFFIcon_64", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property JFFPic_76() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JFFPic_76", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property LPSGIcon_48() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("LPSGIcon_48", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property LPSGPic_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LPSGPic_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property MastodonIcon_48() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("MastodonIcon_48", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property MastodonPic_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MastodonPic_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property OnlyFansIcon_32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("OnlyFansIcon_32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property OnlyFansPic_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OnlyFansPic_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property PinterestIcon_32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("PinterestIcon_32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property PinterestPic_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PinterestPic_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property PornHubIcon_16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("PornHubIcon_16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property PornHubPic_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PornHubPic_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property RedditIcon_128() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("RedditIcon_128", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property RedditPic_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RedditPic_512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property RedGifsIcon_32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("RedGifsIcon_32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property RedGifsPic_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RedGifsPic_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property ThisVidIcon_16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ThisVidIcon_16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ThisVidPic_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ThisVidPic_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property ThreadsIcon_192() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ThreadsIcon_192", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property TikTokIcon_32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("TikTokIcon_32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property TikTokPic_192() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TikTokPic_192", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property TwitterIcon_32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("TwitterIcon_32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property XhamsterIcon_32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("XhamsterIcon_32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property XhamsterPic_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("XhamsterPic_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property XvideosIcon_48() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("XvideosIcon_48", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property XvideosPic_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("XvideosPic_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
